if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

[[ $- != *i* ]] && return

export EDITOR=vim

export MY_PROMPT="node"
export MY_COLOUR="\001\e[0;49;36m\002"

PS1="$MY_COLOUR$MY_PROMPT\001\e[m\002 \W> \[\033[00m\]"
export PS1

